#!/bin/bash -l
#SBATCH --job-name=MRGAdptRem
#SBATCH --output=array_job_out_%A_%a.txt
#SBATCH --error=array_job_err_%A_%a.txt
#SBATCH --account=project_2006079
#SBATCH --partition=small
#SBATCH --time=72:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=12
#SBATCH --mem-per-cpu=12
#SBATCH --array=1-15

#set the input file to process
name=$(sed -n ${SLURM_ARRAY_TASK_ID}p namelistMRG)

module load biokit

#Adapter removal
/projappl/project_2006079/adapterremoval/bin/AdapterRemoval --file1 /scratch/project_2006079/aDNA/step2_FastQScreen/${name}/${name}_1.tagged_filter_fixed1.fastq.gz --fil
e2 /scratch/project_2006079/aDNA/step2_FastQScreen/${name}/${name}_2.tagged_filter_fixed2.fastq.gz --adapter1 AGATCGGAAGAGCACACGTCTGAACTCCAGTCA --adapter2 AGATCGGAAGAGCG
TCGTGTAGGGAAAGAGTGT --basename /scratch/project_2006079/aDNA/step3_AdaptorRemoval/${name}/${name} --collapse --trimns --trimqualities --gzip

#Alignment
bwa mem -t4 -M  /scratch/project_2006079/genomes/Probosciger_aterrimus/GCA_013397665.1_ASM1339766v1.fa /scratch/project_2006079/aDNA/step3_AdaptorRemoval/${name}/${name}
.pair1.truncated.gz /scratch/project_2006079/aDNA/step3_AdaptorRemoval/${name}/${name}.pair2.truncated.gz | samtools view -F4 -hb -o /scratch/project_2006079/aDNA/step4_
preliminary_bams/${name}_${SLURM_ARRAY_TASK_ID}_PE.bam
bwa mem -t4 -M  /scratch/project_2006079/genomes/Probosciger_aterrimus/GCA_013397665.1_ASM1339766v1.fa /scratch/project_2006079/aDNA/step3_AdaptorRemoval/${name}/${name}
.collapsed.gz | samtools view -F4 -hb -o /scratch/project_2006079/aDNA/step4_preliminary_bams/${name}_${SLURM_ARRAY_TASK_ID}_ME.bam
bwa mem -t4 -M  /scratch/project_2006079/genomes/Probosciger_aterrimus/GCA_013397665.1_ASM1339766v1.fa /scratch/project_2006079/aDNA/step3_AdaptorRemoval/${name}/${name}
.collapsed.truncated.gz | samtools view -F4 -hb -o /scratch/project_2006079/aDNA/step4_preliminary_bams/${name}_${SLURM_ARRAY_TASK_ID}_MET.bam

#Permissions
chmod -R 777 *
